### ISSUE TITLE
RGBtoHDMI PLCC model

### ISSUE THREAD

**Issue by krug3rf** [solarmon/RGBtoHDMI#1]
Hi @solarmon ,

I just made my first model and I have an issue, I just see the splashcreen (4 color from start) and nothing more...
I use a LVC574A**D**, do you think it could be the problem ?!
I don't use P1, but I use a external alimentation for testing, but no change.

KR
Fred

**Comment by solarmon** [comment]
Hi @krug3rf 

I use the following logic chips on my boards:

U2/U3: Texas Instruments SN74LVC574ADW Octal D Type Flip Flop IC, 3-State, 20-Pin SOIC
U1: Texas Instruments SN74LVC86ADR, Quad 2-Input XOR Logic Gate, 14-Pin SOIC

What is the full part number of your chips?

Can you show how you have built it - especially the PLCC socket - this has to be in the correct orientation.

Use a multimeter to check the identified Denise pins (the ones circled) to where they should be on the motherboard - especially the CSYNC and 7M signals.

**Comment by krug3rf** [comment]
All continuties from U1/U2/U3 have been tested and are OK.
I check again to answer when I will back home (I'm at office) ;)

**Comment by solarmon** [comment]
@krug3rf Do you still have this issue? If you can provide more information then I can try to help you resolve it.

**Comment by krug3rf** [comment]
Hi, I'm back home this weekend and do it ;)
thanks for your help :)

**Comment by krug3rf** [comment]
I have a question for you about the PLCC 52, do you use sandpaper or a hand
tool (like a dremel) to modify it ?
Your model is an Augat PCS-052A or a generic ?

**Comment by solarmon** [comment]
@krug3rf For the PLCC-52socket mod, all I did was to cut the plastic standoffs inside the socket. I just use some small wire side cutters, but it is not so good - so a Dremel type tool is probably the better/recommended option.

I don't know what 'model' my PLCC-52 socket is - it is just a no brand one that I purchased on eBay.

**Comment by krug3rf** [comment]
Interesting !
ok, I will try only this and not remove 0,5 or 1mm one the upper side of
the PLCC

**Comment by krug3rf** [comment]
It's aliveeeeee lol
A short circuit on U1 between 2 pins... Zooooom zooooom ;)

Thanks for your work and your help !
Now I have ten models on going for french community ;)

Fred

**Comment by solarmon** [comment]
Glad you figured out the issue!

Thanks for trying out my design. I've got a lower profile SMT based one that I need to test out. Also a design that is just a SMT PLCC hat that uses an FPC cable going a CPLD based RGBtoHDMI board that could be mounted elsewhere.

**Comment by krug3rf** [comment]
I'm excited ^^
Can you share some beta previews of your new projects (I keep this for me,
promise :p) ?

**Comment by krug3rf** [comment]
*excited lol

Le sam. 1 mai 2021 à 11:55, Frédéric Campos ***@***.***> a
écrit :

**Comment by solarmon** [comment]
@krug3rf I can give you some teaser pictures!

![image](https://user-images.githubusercontent.com/46369787/116809175-b350d400-ab34-11eb-94d8-9d7dd61ec3a4.png)

![image](https://user-images.githubusercontent.com/46369787/116809226-e4c99f80-ab34-11eb-97ad-085cb125889b.png)

![image](https://user-images.githubusercontent.com/46369787/116809272-0fb3f380-ab35-11eb-8d86-8e91adb788af.png)

**Comment by krug3rf** [comment]
Sexy ^^
so with this model Furia accelerator could be added ?
There is a CPLD... hum hum...

**Comment by solarmon** [comment]
CPLD solution design is from LinuxJedi, I'm just re-mixing it to a new footprint.

I have not got a Furia accelerator to test, so I don't know if this PLCC FFC hat design will be low profile enough.
