### ISSUE TITLE
Rev 2 board doesn't fit on Rev 3 Amiga 500 motherboards

### ISSUE THREAD

**Issue by MatGrump** [solarmon/RGBtoHDMI#3]
The inductor LF1 is lower on Rev 3 boards and doesn't allow for installation of the REV 2 RGD2HDMI board. See attached images

https://imgur.com/a/YwSwP5C

![311288252_3400786653488147_4468245213283890169_n](https://user-images.githubusercontent.com/77683120/194884183-f2215b7f-4407-420e-b8fe-bab1c7f66cd0.jpg)
![309898826_608775794322786_1738650730408694813_n](https://user-images.githubusercontent.com/77683120/194884206-fbcb7926-ca17-4dc1-9e85-ee739eb18217.jpg)

**Comment by solarmon** [comment]
Hi,

That is not one of my RGBtoHDMI board for the A500.

It looks like it is from PM Developments:

https://www.facebook.com/PMDevelopments/
https://www.instagram.com/pmdevelopments/

You'll have to raise that with that developer.

**Comment by MatGrump** [comment]
yes sorry. I noticed after i posted it. It looks like yours has taken this into consideration.

**Comment by solarmon** [comment]
No worries. I can't remember whether I actually tested with a rev 3 board - I'll have to dig it out to check!

**Comment by MatGrump** [comment]
No problem, if you need me to measure anything please let me know.

**Comment by solarmon** [comment]
Actually, I don't have a rev 3. I was thinking of a rev 5, which I do have.

Using an image I found of the rev 3, I overlayed an image of my latest RGBtoHDMI A500 board, and that looks like it wouldn't fit either:

![image](https://user-images.githubusercontent.com/46369787/194933540-e6c704e2-b2b2-4c58-a5d9-8bccb6fa81d2.png)

The coil is definitely much lower in a rev 3 board!

I can think of three options you might have:

1. Use the original RGBtoHDMI board design, which doesn't have a pi relocator.

2. Use my RGBtoHDMI Amiga Denise CPLD FFC Rev 1.1 (https://github.com/solarmon/RGBtoHDMI#rgbtohdmi-amiga-denise-cpld-ffc-rev-11) with a RGBtoHDMI Amiga Denise DIP Breakout FFC (https://github.com/solarmon/RGBtoHDMI#rgbtohdmi-amiga-denise-dip-breakout-ffc).

3. Replace the Denise socket on the RGBtoHDMI board with ones with longer pins that pass straight through. This shift down the board a bit, which MIGHT work. I use such a socket for my RGBtoHDMI CDTV solution and it also makes it a bit lower profile.

**Comment by solarmon** [comment]
The latest LinuxJedi design, looks like it should support rev 3 motherboards:

https://github.com/LinuxJedi/AmigaRGBtoHDMI/tree/main/Amiga500CPLD

**Comment by MatGrump** [comment]
Some good solutions. I have the option to return this board and get another which is probably what I will do for now while I think about a different solution. The LinuxJedi looks like the simplest way forward but they are out of stock.

Thanks for all the help, even though it wasn't even your board. Very much appreciated.

**Comment by Retrofletch** [comment]
I made a longer version based on the old linuxjedi version that i think also would fit.
![longboy_rev3](https://user-images.githubusercontent.com/69827231/203059663-9772dc32-5ee1-4e9d-9ec5-7548dc253ea1.png)

and there is also this version that should fit:
https://github.com/nobodyisinocent/RGBtoHDMI#tiny-rgb2hdmi-cpld-design-

Just for future reference :)

**Comment by ehalebi** [comment]
@solarmon is it possible to make a Extralong version of CPLD 500 PCB with your FF addons? Retrofletch has one, but without FF OSD support.

regards

**Comment by Retrofletch** [comment]
It would be quite easy to make solarmons design a bit longer to fit but i just dont have the time at this moment

**Comment by ehalebi** [comment]
@solarmon is that something you could do?
Maybe 5-8cm longer. So a lot of people got a Gotek drive and want to add also HDMI to their A500s. And if you also got an accelerator card sitting on a 90 degree Relocator, than this will be the BEST RGB2HDMI Solution .

only thing missing is still an onboard audio embedder/injector for all of the RGB2HDMI PCBs.

**Comment by ehalebi** [comment]
I have bought an audio Inserter for installing it internally in my A500
![image](https://github.com/solarmon/RGBtoHDMI/assets/142666739/79bf0d71-0f00-4de8-8c98-29f996a0f8b3)

**Comment by solarmon** [comment]
@ehalebi 

It can certainly be done, but unfortunately, this is not high my list (if at all). Probably the only reason I would work on this again, is to create a PLCC version of it.

Regards,

Mon

**Comment by ehalebi** [comment]
Do I need to buy software to do this?

regards

**Comment by solarmon** [comment]
@ehalebi 

> Do I need to buy software to do this?
> 
> regards

To do what?

**Comment by ehalebi** [comment]
To extend manually the length of your PCB? Or is there decent freeware to do such kind of jobs. I would probably try my own.

**Comment by solarmon** [comment]
@ehalebi 

The PCB design was done using KiCAD, which is an open source application - https://www.kicad.org/

But be warned - it is a very steep learning curve if you don't already have experience in PCB design.
