### ISSUE TITLE
Getting a no sync issue

### ISSUE THREAD

**Issue by luvwagn** [solarmon/RGBtoHDMI#4]
I'm wondering if instructions are still correct, regarding the amiga_cpld folder etc.

My cdtv rgbtohdmi is working, amiga is working via db23 video port, but I can't get a sync signal?

I can see workbench, but auto configure doesn't work, and I can't get a solid signal...

![Screenshot_20230701-143821_Gallery](https://github.com/solarmon/RGBtoHDMI/assets/66340230/a1966c38-c3cc-49da-be64-1bd7eb7ad4f0)

**Comment by solarmon** [comment]
Hi,

For the purpose of this ticket, please provide some context:

* What RGBtoHDMI adapter have you got?
* Where did you buy it from (or whether you built it yourself)?
* Which Amiga it is being used on, and what Denise chip does it have?

Please provide some clear pictures of your RGBtoHDMI board/adapter and setup.

**Comment by luvwagn** [comment]
- CDTV rev2.2, NTSC
- OCS denise (8362R8)
- DB23 to VGA video out working fine
- Solarmon v1 design (no mouse ports)
- Built by RetroFletch, sold via Tindie.
- - Seller is willing to do return, but I'd like to troubleshoot 1st, as sending back to Europe is time consuming / costly.
- Pi Zero W v1.1, tried two
- SD card prepped with May release from Hoglet github
- tried card content as unzipped, chose Amiga profile, ensure CPLD FW is v94 12-bit rgb
- also tried moving content of amiga_cpld_readme/amiga_cpld_setup to root of drive. Unclear if this is required at all with the new profile stuff in 5/17 release

None of the above results in a solid image, but I can see the content changing from cdtv insertion animation, to wb3.2.x (ntsc mode)
![20230702_133918](https://github.com/solarmon/RGBtoHDMI/assets/66340230/9cc55658-41f9-4035-9a0b-ab7fed84b62b)
![20230702_133912](https://github.com/solarmon/RGBtoHDMI/assets/66340230/83164600-2d27-4372-b0b7-45071fb9b376)

Based on schematics, looked at csync signal to pin 32 on Denise, attached. I may not have gotten a good capture. Not sure what csync should look like.
![20230702_145350](https://github.com/solarmon/RGBtoHDMI/assets/66340230/3a5440e4-2ee3-4ca0-94c3-2c5c2e8415e8)

**Comment by Retrofletch** [comment]
I sent him a copy of my own SD card i use for testing these, it will help rule out issue with his software setup.
I also asked him to test contuinity between csync on both ribbon cable connectors to rule out bad cable / connection.
if these are not issue im gonna assume i borked something up hardware wise, i always test before send ofcourse but it could have been a badly soldered connection or similar that got loose in shipping or while installing. it happens =/
Better not waste too much time troubleshooting and just send back if the obvious easy to test things dont sort it out.

**Comment by solarmon** [comment]
@luvwagn 

Apologies for the delay in replying.

For the Denise adapter FFC connector, it looks different my my normal design and build - which has the contacts at the bottom - so the FFC flex cable has the contacts at the bottom and the blue side facing up (maybe @Retrofletch can confirm). This also the same at the RGBtoHDMI board end too.

**Comment by luvwagn** [comment]
As mentioned in email, it depends on the connectors. With blue up at both ends, I get a black screen. With blue down at both ends, I get some correct  but garbled output.

Your design has the cables under black connectors and blue up, but different choice of connectors like used here means black underneath and blue down.

**Comment by solarmon** [comment]
@luvwagn 

All I can suggest is to check the flex connector pins on the Denise adapter and on the RGBtoHDMI board; and also check the pins on the CPLD chip- check that there are no cold joints and they are not shorted together.

**Comment by luvwagn** [comment]
@solarmon - the fw releases from Ian / hoglet etc have an "Amiga_CPLD" folder - is any action required regarding that folder, on your design?  It references "LinuxJedi" designs as needing things done regarding that folder...

**Comment by luvwagn** [comment]
> @luvwagn
> 
> All I can suggest is to check the flex connector pins on the Denise adapter and on the RGBtoHDMI board; and also check the pins on the CPLD chip- check that there are no cold joints and they are not shorted together.

Have done so - there is full CSYNC continuity between the denise pin, ribbon header on Denise Board, and ribbon header on RGB2HDMI board.  Checked other connections as well, have full continuity

**Comment by solarmon** [comment]
@luvwagn 

Please point to where it "needing things done regarding that folder" - I'm not sure what you mean.

You seem to have the software running correctly - so I'm not suspecting that. It just seems the signal to/from the CPLD chip is possibly shorted or not connected somewhere. Sorry, there is nothing else I can suggest.

**Comment by luvwagn** [comment]
There is an amiga_cpld_readme folder at the root of the zip file.  it doesn't matter if i perform those actions or not, i get the same "no sync found" problem.  I believe those actions just set the defaults to 1-button mode and an Amiga setting.

I checked the CSYNC signal from U1 Pin 3+4 to Denise to Denise Carrier PCB with ribbon connector, to RGB2HDMI board, to CPLD pin.  I have continuity through the entire path.

Is it possible somehow that CSYNC is incorrect?  That doesn't make sense to me, as regular RGB output is working...
________________________________

**Comment by luvwagn** [comment]
> I sent him a copy of my own SD card i use for testing these, it will help rule out issue with his software setup. I also asked him to test contuinity between csync on both ribbon cable connectors to rule out bad cable / connection. if these are not issue im gonna assume i borked something up hardware wise, i always test before send ofcourse but it could have been a badly soldered connection or similar that got loose in shipping or while installing. it happens =/ Better not waste too much time troubleshooting and just send back if the obvious easy to test things dont sort it out.

Hi Retrofletch!  Tindie is probably broken again for sending you notifications.  Wondering how the returned board is going, and if you could reproduce my behaviour or not...

**Comment by Retrofletch** [comment]
It works just fine but i tend to respond only once i have an update, you can also reach me by mail retrofletch@outlook.com so we dont annoy solarmon by all this offtopic.
