### ISSUE TITLE
RPi not booting with CPLD RGB to HDMI

### ISSUE THREAD

**Issue by bmthr** [solarmon/RGBtoHDMI#6]
Hi all,

My problem is that my RPi ZERO WH not working wiith CPLD RGB to HDMI adapter on Amiga 500. RPi 1.3 work well with this adapter and RPi WH working well with TTL adapter. 
RPi WH if not connected to CPLD adapter board show menu _CPLD not fitted_, but when I connect it to CPLD board stuck on empty black screen.

Did I miss some settings? Any help about my problem?

Thank You!

**Comment by solarmon** [comment]
Hi @bmthr 

Which of my RGBtoHDMI board have you got? Did you build it yourself or buy it from somebody?

Please can you show a picture of the issue you are seeing.

**Comment by bmthr** [comment]
I build it by myself, I build almost 200 boards TTL and CPLD and never found problem like this...

Pictures if CPLD board and RPi attached...
![20231016_103255](https://github.com/solarmon/RGBtoHDMI/assets/77853161/abbd6111-8119-469c-b191-aa89b72e8547)
![20231016_103325](https://github.com/solarmon/RGBtoHDMI/assets/77853161/ae5461c5-ba5e-4123-99c4-bc98f558dbb0)
![20231016_103520](https://github.com/solarmon/RGBtoHDMI/assets/77853161/d5de3bbb-d339-4865-8b25-aeaff16cdd45)

**Comment by bmthr** [comment]
When I connect all to Amiga, screen is black, there is no any message or info on screen even button not work. If I connect only RPi to HDMI and connect power supply I get message CPLD not fitted. As I say before, when I put this RPi to Small TTL RGBtoHDMI adapter all is working well.

**Comment by solarmon** [comment]
Hi @bmthr 

This is not one of my RGBtoHDMI board designs - it is one from LinuxJedi.

Normally, when I have issues with the a CPLD based RGBtoHDMI board, it is because there is a cold solder joint on one of the pullup resistors or capacitors, or (a cold joint or short) on a CPLD pin.

**Comment by bmthr** [comment]
Yes, I know that, but I tested this Rpi with other CPLD board (have it 3 on stock now) and problem is same, but all boards work fine with RPi v1.3

**Comment by solarmon** [comment]
What RGBtoHDMI firmware version are you using?

Get the latest stable version from:

https://github.com/hoglet67/RGBtoHDMI/releases

or the latest beta versions from:

https://github.com/IanSB/RGBtoHDMI/releases

I've have also come across issues where the CPLD RGBtoHDMI board did not work until you tried a different microSD card on the Pi.
